//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StomKarta.Properties {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("StomKarta.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Private rights. 2018-2020 All rights reserved..
        /// </summary>
        public static string aboutAllRights {
            get {
                return ResourceManager.GetString("aboutAllRights", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Developer: Zourawsky Vladimir, tel. +7 (916) 288-1275.
        /// </summary>
        public static string aboutAuthor {
            get {
                return ResourceManager.GetString("aboutAuthor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Contens information abour reception:.
        /// </summary>
        public static string aboutContens {
            get {
                return ResourceManager.GetString("aboutContens", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на - records, containing information about orthopedic reception..
        /// </summary>
        public static string aboutContensOrth {
            get {
                return ResourceManager.GetString("aboutContensOrth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на - records, containing information about patients,.
        /// </summary>
        public static string aboutContensPac {
            get {
                return ResourceManager.GetString("aboutContensPac", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на - records, containing information about profilactic reception,.
        /// </summary>
        public static string aboutContensProf {
            get {
                return ResourceManager.GetString("aboutContensProf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на - records, containing information about surgeon reception,.
        /// </summary>
        public static string aboutContensSurg {
            get {
                return ResourceManager.GetString("aboutContensSurg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на - records, containing information about therapy reception,.
        /// </summary>
        public static string aboutContensTher {
            get {
                return ResourceManager.GetString("aboutContensTher", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Intended for recording stomatologic reception..
        /// </summary>
        public static string aboutIntended {
            get {
                return ResourceManager.GetString("aboutIntended", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на This program reserved international and other rights..
        /// </summary>
        public static string aboutRights0 {
            get {
                return ResourceManager.GetString("aboutRights0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Don`t copy..
        /// </summary>
        public static string aboutRights1 {
            get {
                return ResourceManager.GetString("aboutRights1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Don`t disturb..
        /// </summary>
        public static string aboutRights2 {
            get {
                return ResourceManager.GetString("aboutRights2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Version.
        /// </summary>
        public static string aboutVersion {
            get {
                return ResourceManager.GetString("aboutVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на None.
        /// </summary>
        public static string baseNone {
            get {
                return ResourceManager.GetString("baseNone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Orthopedic.
        /// </summary>
        public static string baseOrthoped {
            get {
                return ResourceManager.GetString("baseOrthoped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Profilactic.
        /// </summary>
        public static string baseProfilactic {
            get {
                return ResourceManager.GetString("baseProfilactic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Reestr.
        /// </summary>
        public static string baseReestr {
            get {
                return ResourceManager.GetString("baseReestr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Surgeon.
        /// </summary>
        public static string baseSurgeon {
            get {
                return ResourceManager.GetString("baseSurgeon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Therapy.
        /// </summary>
        public static string baseTherapy {
            get {
                return ResourceManager.GetString("baseTherapy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на User.
        /// </summary>
        public static string baseUser {
            get {
                return ResourceManager.GetString("baseUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на About program StomBase.
        /// </summary>
        public static string formAboutTitle {
            get {
                return ResourceManager.GetString("formAboutTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Authorization.
        /// </summary>
        public static string formLogonTitle {
            get {
                return ResourceManager.GetString("formLogonTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Dental records.
        /// </summary>
        public static string formMainTitle {
            get {
                return ResourceManager.GetString("formMainTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Search for similar patients in the database.
        /// </summary>
        public static string formPacFindTitle {
            get {
                return ResourceManager.GetString("formPacFindTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Add new pacient.
        /// </summary>
        public static string formPacientAddTitle {
            get {
                return ResourceManager.GetString("formPacientAddTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Edit current pacient.
        /// </summary>
        public static string formPacientEditTitle {
            get {
                return ResourceManager.GetString("formPacientEditTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Confirm password.
        /// </summary>
        public static string logonLabelConfirm {
            get {
                return ResourceManager.GetString("logonLabelConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Password.
        /// </summary>
        public static string logonLabelPass {
            get {
                return ResourceManager.GetString("logonLabelPass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на User.
        /// </summary>
        public static string logonLabelUser {
            get {
                return ResourceManager.GetString("logonLabelUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Please confirm password for checking..
        /// </summary>
        public static string logonMessageConfirm {
            get {
                return ResourceManager.GetString("logonMessageConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Password and Confirm password not equal. Please try again..
        /// </summary>
        public static string logonMessageConfirmError {
            get {
                return ResourceManager.GetString("logonMessageConfirmError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Password incorrect. Please try again..
        /// </summary>
        public static string logonMessageWrongPassword {
            get {
                return ResourceManager.GetString("logonMessageWrongPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Add pacient.
        /// </summary>
        public static string mainButtonContentAdd {
            get {
                return ResourceManager.GetString("mainButtonContentAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Edit pacient.
        /// </summary>
        public static string mainButtonContentEdit {
            get {
                return ResourceManager.GetString("mainButtonContentEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Adress.
        /// </summary>
        public static string mainLabelAdress {
            get {
                return ResourceManager.GetString("mainLabelAdress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Age.
        /// </summary>
        public static string mainLabelAge {
            get {
                return ResourceManager.GetString("mainLabelAge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Comment.
        /// </summary>
        public static string mainLabelComment {
            get {
                return ResourceManager.GetString("mainLabelComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на E-Mail.
        /// </summary>
        public static string mainLabelEMail {
            get {
                return ResourceManager.GetString("mainLabelEMail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на From and description.
        /// </summary>
        public static string mainLabelFrom {
            get {
                return ResourceManager.GetString("mainLabelFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Pseudonym.
        /// </summary>
        public static string mainLabelNickName {
            get {
                return ResourceManager.GetString("mainLabelNickName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Telefons.
        /// </summary>
        public static string mainLabelTelefons {
            get {
                return ResourceManager.GetString("mainLabelTelefons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на years..
        /// </summary>
        public static string mainLabelYears {
            get {
                return ResourceManager.GetString("mainLabelYears", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Error when adding patient data to the database.
        /// </summary>
        public static string mainMessageErrorAddingPacient {
            get {
                return ResourceManager.GetString("mainMessageErrorAddingPacient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Exit.
        /// </summary>
        public static string menuExit {
            get {
                return ResourceManager.GetString("menuExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на About.
        /// </summary>
        public static string menuItemAbout {
            get {
                return ResourceManager.GetString("menuItemAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Configuration.
        /// </summary>
        public static string menuItemConfiguration {
            get {
                return ResourceManager.GetString("menuItemConfiguration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Help.
        /// </summary>
        public static string menuItemHelp {
            get {
                return ResourceManager.GetString("menuItemHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на View help.
        /// </summary>
        public static string menuItemHelpView {
            get {
                return ResourceManager.GetString("menuItemHelpView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Reestr.
        /// </summary>
        public static string menuItemReestr {
            get {
                return ResourceManager.GetString("menuItemReestr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Reestr of pacients.
        /// </summary>
        public static string menuItemReestrPacient {
            get {
                return ResourceManager.GetString("menuItemReestrPacient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Settings.
        /// </summary>
        public static string menuItemSettings {
            get {
                return ResourceManager.GetString("menuItemSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Users.
        /// </summary>
        public static string menuItemUser {
            get {
                return ResourceManager.GetString("menuItemUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на User Add.
        /// </summary>
        public static string menuItemUserAdd {
            get {
                return ResourceManager.GetString("menuItemUserAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на List.
        /// </summary>
        public static string menuItemUserList {
            get {
                return ResourceManager.GetString("menuItemUserList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Vizits.
        /// </summary>
        public static string menuItemVizit {
            get {
                return ResourceManager.GetString("menuItemVizit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Orthopedist.
        /// </summary>
        public static string menuItemVizitOrthopedist {
            get {
                return ResourceManager.GetString("menuItemVizitOrthopedist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Profilactic.
        /// </summary>
        public static string menuItemVizitProfilactic {
            get {
                return ResourceManager.GetString("menuItemVizitProfilactic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Surgeon.
        /// </summary>
        public static string menuItemVizitSurgeon {
            get {
                return ResourceManager.GetString("menuItemVizitSurgeon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Therapist.
        /// </summary>
        public static string menuItemVizitTherapist {
            get {
                return ResourceManager.GetString("menuItemVizitTherapist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Error.
        /// </summary>
        public static string messageCaptionError {
            get {
                return ResourceManager.GetString("messageCaptionError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Information.
        /// </summary>
        public static string messageCaptionInformation {
            get {
                return ResourceManager.GetString("messageCaptionInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Adding.
        /// </summary>
        public static string modeAdd {
            get {
                return ResourceManager.GetString("modeAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Browse.
        /// </summary>
        public static string modeBrowse {
            get {
                return ResourceManager.GetString("modeBrowse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Edit.
        /// </summary>
        public static string modeEdit {
            get {
                return ResourceManager.GetString("modeEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Closed.
        /// </summary>
        public static string modeNone {
            get {
                return ResourceManager.GetString("modeNone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на No.
        /// </summary>
        public static string pacFindButtonNo {
            get {
                return ResourceManager.GetString("pacFindButtonNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Yes.
        /// </summary>
        public static string pacFindButtonYes {
            get {
                return ResourceManager.GetString("pacFindButtonYes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Based on the entered: Name, Surname and the DB patients was not found..
        /// </summary>
        public static string pacFindMessageTableEmpty {
            get {
                return ResourceManager.GetString("pacFindMessageTableEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на You entered:.
        /// </summary>
        public static string pacFindText0 {
            get {
                return ResourceManager.GetString("pacFindText0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Similar records were found in the database..
        /// </summary>
        public static string pacFindText1 {
            get {
                return ResourceManager.GetString("pacFindText1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на No similar entries were found in the database..
        /// </summary>
        public static string pacFindText10 {
            get {
                return ResourceManager.GetString("pacFindText10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на View the list if you already have such a patient,.
        /// </summary>
        public static string pacFindText2 {
            get {
                return ResourceManager.GetString("pacFindText2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на then you don&apos;t need to add it..
        /// </summary>
        public static string pacFindText3 {
            get {
                return ResourceManager.GetString("pacFindText3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Add a patient to the database?.
        /// </summary>
        public static string pacFindTextBlockAsk {
            get {
                return ResourceManager.GetString("pacFindTextBlockAsk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Add Tel.
        /// </summary>
        public static string pacientButtonAddTel {
            get {
                return ResourceManager.GetString("pacientButtonAddTel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Del Tel.
        /// </summary>
        public static string pacientButtonDelTel {
            get {
                return ResourceManager.GetString("pacientButtonDelTel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Exit.
        /// </summary>
        public static string pacientButtonExit {
            get {
                return ResourceManager.GetString("pacientButtonExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Save.
        /// </summary>
        public static string pacientButtonSave {
            get {
                return ResourceManager.GetString("pacientButtonSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на #.
        /// </summary>
        public static string pacientGridHeader0 {
            get {
                return ResourceManager.GetString("pacientGridHeader0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Fam.
        /// </summary>
        public static string pacientGridHeader1 {
            get {
                return ResourceManager.GetString("pacientGridHeader1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на First Name.
        /// </summary>
        public static string pacientGridHeader2 {
            get {
                return ResourceManager.GetString("pacientGridHeader2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Last Name.
        /// </summary>
        public static string pacientGridHeader3 {
            get {
                return ResourceManager.GetString("pacientGridHeader3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Sex.
        /// </summary>
        public static string pacientGridHeader4 {
            get {
                return ResourceManager.GetString("pacientGridHeader4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Date Birth.
        /// </summary>
        public static string pacientGridHeader5 {
            get {
                return ResourceManager.GetString("pacientGridHeader5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Changed.
        /// </summary>
        public static string pacientGridHeader6 {
            get {
                return ResourceManager.GetString("pacientGridHeader6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на By:.
        /// </summary>
        public static string pacientGridHeader7 {
            get {
                return ResourceManager.GetString("pacientGridHeader7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Address.
        /// </summary>
        public static string pacientLabelAddress {
            get {
                return ResourceManager.GetString("pacientLabelAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Comment.
        /// </summary>
        public static string pacientLabelComment {
            get {
                return ResourceManager.GetString("pacientLabelComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Birthday.
        /// </summary>
        public static string pacientLabelDR {
            get {
                return ResourceManager.GetString("pacientLabelDR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на E-Mail.
        /// </summary>
        public static string pacientLabelEMail {
            get {
                return ResourceManager.GetString("pacientLabelEMail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Family name.
        /// </summary>
        public static string pacientLabelFam {
            get {
                return ResourceManager.GetString("pacientLabelFam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на From Comment.
        /// </summary>
        public static string pacientLabelFromComment {
            get {
                return ResourceManager.GetString("pacientLabelFromComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на First name.
        /// </summary>
        public static string pacientLabelIm {
            get {
                return ResourceManager.GetString("pacientLabelIm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на NickName.
        /// </summary>
        public static string pacientLabelNickName {
            get {
                return ResourceManager.GetString("pacientLabelNickName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Number.
        /// </summary>
        public static string pacientLabelNumber {
            get {
                return ResourceManager.GetString("pacientLabelNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Second name.
        /// </summary>
        public static string pacientLabelOtc {
            get {
                return ResourceManager.GetString("pacientLabelOtc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на PrivateUserInfo.
        /// </summary>
        public static string pacientLabelPrivateUserInfo {
            get {
                return ResourceManager.GetString("pacientLabelPrivateUserInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Sex.
        /// </summary>
        public static string pacientLabelSex {
            get {
                return ResourceManager.GetString("pacientLabelSex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Telefons.
        /// </summary>
        public static string pacientLabelTelefons {
            get {
                return ResourceManager.GetString("pacientLabelTelefons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на +7 (000) 000-00-00.
        /// </summary>
        public static string pacientLabelTelFormat {
            get {
                return ResourceManager.GetString("pacientLabelTelFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на It isn`t digit character..
        /// </summary>
        public static string pacientMessageNotDigit {
            get {
                return ResourceManager.GetString("pacientMessageNotDigit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Required fields empty..
        /// </summary>
        public static string pacientMessageRequiredEmpty {
            get {
                return ResourceManager.GetString("pacientMessageRequiredEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Telefon number incorrect, try again..
        /// </summary>
        public static string pacientMessageWrongTelNumber {
            get {
                return ResourceManager.GetString("pacientMessageWrongTelNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Mandatory fields..
        /// </summary>
        public static string pacientTextBlockRequired {
            get {
                return ResourceManager.GetString("pacientTextBlockRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Card of Dental patient.
        /// </summary>
        public static string programName {
            get {
                return ResourceManager.GetString("programName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Base:.
        /// </summary>
        public static string statusBarItemBaseLabel {
            get {
                return ResourceManager.GetString("statusBarItemBaseLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Mode:.
        /// </summary>
        public static string statusBarItemModeLabel {
            get {
                return ResourceManager.GetString("statusBarItemModeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на User:.
        /// </summary>
        public static string statusBarItemUserLabel {
            get {
                return ResourceManager.GetString("statusBarItemUserLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на None.
        /// </summary>
        public static string statusBarItemUserStatus {
            get {
                return ResourceManager.GetString("statusBarItemUserStatus", resourceCulture);
            }
        }
    }
}
